{
    "comments": [
        {
            "author": "Robert Muir",
            "body": "Patch that creates a RemoteTestCaseJ4 that binds to an ephemeral port (0), with a custom\nRMIServerSocketFactory that has access to the port number.\n\n_TestUtil.getRandomSocketPort() is removed, and all remote tests extend this new class.",
            "date": "2010-04-10T21:15:31.265+0000",
            "id": 0
        },
        {
            "author": "Robert Muir",
            "body": "Committed revision 932795.\n",
            "date": "2010-04-10T21:38:50.288+0000",
            "id": 1
        },
        {
            "author": "Uwe Schindler",
            "body": "Looks fine! +1 to commit!",
            "date": "2010-04-10T21:41:05.390+0000",
            "id": 2
        },
        {
            "author": "Robert Muir",
            "body": "backported: revision 941659",
            "date": "2010-05-06T11:02:49.878+0000",
            "id": 3
        },
        {
            "author": "Grant Ingersoll",
            "body": "Bulk close for 3.1",
            "date": "2011-03-30T15:50:19.001+0000",
            "id": 4
        }
    ],
    "component": "modules/other",
    "description": "The contrib/remote tests will fail randomly.\n\nThis is because they use this _TestUtil.getRandomSocketPort() which\nsimply generates a random number, but if this is already in use, it will fail.\n\nAdditionally there is duplicate RMI logic across all 3 test classes.",
    "hasPatch": true,
    "hasScreenshot": false,
    "id": "LUCENE-2390",
    "issuetypeClassified": "OTHER",
    "issuetypeTracker": "BUG",
    "priority": "Major",
    "product": "LUCENE",
    "project": "LUCENE",
    "summary": "contrib/remote tests fail randomly",
    "systemSpecification": true,
    "version": "3.1"
}