{
    "comments": [
        {
            "author": "S\u00e9bastien Launay",
            "body": "Patch for logging the exception and fixing iterater typo.",
            "date": "2008-03-20T16:41:45.698+0000",
            "id": 0
        },
        {
            "author": "Dominique Pfister",
            "body": "Thanks for reporting and providing a patch! Fixed in trunk (641210) and 1.4 branch (641209).",
            "date": "2008-03-26T08:59:47.420+0000",
            "id": 1
        }
    ],
    "component": "clustering, jackrabbit-core",
    "description": "When our MySQL server is down or failed queries we have the following log :\nERROR (ClusterNode-node1) [org.apache.jackrabbit.core.cluster.ClusterNode] Periodic sync of journal failed: Unable to return record iterater.\n\nSo the root exception (SQLException in my case) is missing from the log and this prevent me from quickly finding the reason.",
    "hasPatch": true,
    "hasScreenshot": false,
    "id": "JCR-1493",
    "issuetypeClassified": "IMPROVEMENT",
    "issuetypeTracker": "IMPROVEMENT",
    "priority": "Major",
    "product": "JACKRABBIT",
    "project": "JACKRABBIT",
    "summary": "Root exception not logged in ClusterNode for ClusterException",
    "systemSpecification": true,
    "version": "core 1.4.1"
}