{
    "comments": [
        {
            "author": "Alexander Klimetschek",
            "body": "+1",
            "date": "2008-10-21T07:57:18.574+0000",
            "id": 0
        },
        {
            "author": "Jukka Zitting",
            "body": "+1",
            "date": "2008-11-28T13:28:23.573+0000",
            "id": 1
        },
        {
            "author": "Jukka Zitting",
            "body": "How about this alternative patch that makes sanityCheck() directly throw a RepositoryException? This way we don't need to explicitly catch and rethrow the exception.\n\nNote that I also removed the sanityCheck() call from a few protected getter methods. Public methods that cause those getters to be invoked have already called sanityCheck, so it's safe to drop these extra calls.",
            "date": "2009-01-09T15:20:27.275+0000",
            "id": 2
        },
        {
            "author": "Felix Meschberger",
            "body": "Looks good to me, too, and makes perfect sense.",
            "date": "2009-01-09T15:30:04.754+0000",
            "id": 3
        },
        {
            "author": "Jukka Zitting",
            "body": "Patch applied in revision 733080. Targeting for 1.5.1.",
            "date": "2009-01-09T16:51:14.789+0000",
            "id": 4
        },
        {
            "author": "Gr\u00e9gory Joseph",
            "body": "I might be wrong, but I seem to remember this is the exception i got with JCR-1778, which might thus be irrelevant now ?",
            "date": "2009-01-12T16:30:21.554+0000",
            "id": 5
        },
        {
            "author": "Jukka Zitting",
            "body": "Merged also to the 1.4 branch in revision 734370.",
            "date": "2009-01-14T12:44:55.563+0000",
            "id": 6
        }
    ],
    "component": "jackrabbit-core",
    "description": "Calling any login method on Repository instance, which has been shut down throws an IllegalStateException, which is caused by the RepositoryImpl.sanityCheck method.\n\nThis exception is unexpected by callers of the login method, which is specified to throw one of LoginException, NoSuchWorkspaceException and RepositoryException. In particular the spec says, that a RepositoryException is thrown \"if another error occurs\".\n\nSo I suggest to modify the RepositoryImpl.login(Credentials, String) as follows (patch against trunk):\n\nIndex: /usr/src/jackrabbit/trunk/jackrabbit-core/src/main/java/org/apache/jackrabbit/core/RepositoryImpl.java\n===================================================================\n--- /usr/src/jackrabbit/trunk/jackrabbit-core/src/main/java/org/apache/jackrabbit/core/RepositoryImpl.java\t(revision 706543)\n+++ /usr/src/jackrabbit/trunk/jackrabbit-core/src/main/java/org/apache/jackrabbit/core/RepositoryImpl.java\t(working copy)\n@@ -1358,6 +1358,8 @@\n         } catch (AccessDeniedException ade) {\n             // authenticated subject is not authorized for the specified workspace\n             throw new LoginException(\"Workspace access denied\", ade);\n+        } catch (RuntimeException re) {\n+            throw new RepositoryException(re.getMessage(), re);\n         } finally {\n             shutdownLock.readLock().release();\n         }\n",
    "hasPatch": true,
    "hasScreenshot": false,
    "id": "JCR-1823",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "Major",
    "product": "JACKRABBIT",
    "project": "JACKRABBIT",
    "summary": "Repository.login throws IllegalStateException",
    "systemSpecification": true,
    "version": "core 1.4.5"
}